var that=this;function __skpm_run(t,e){that.context=e;var n=function(t){var e={};function n(r){if(e[r])return e[r].exports;var i=e[r]={i:r,l:!1,exports:{}};return t[r].call(i.exports,i,i.exports,n),i.l=!0,i.exports}return n.m=t,n.c=e,n.d=function(t,e,r){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:r})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var i in t)n.d(r,i,function(e){return t[e]}.bind(null,i));return r},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s="./src/sketch/refresh.js")}({"./src/sketch/helpers/constants.js":
/*!*****************************************!*\
  !*** ./src/sketch/helpers/constants.js ***!
  \*****************************************/
/*! exports provided: SETTINGS_LICENSE, SETTINGS_STATUS, SETTINGS_EMAIL, SETTINGS_FREQUENCY, SETTINGS_VERIFICATION, SETTINGS_MIXPANELID, URL_PRICING, URL_SUPPORT */function(t,e,n){"use strict";n.r(e),n.d(e,"SETTINGS_LICENSE",function(){return r}),n.d(e,"SETTINGS_STATUS",function(){return i}),n.d(e,"SETTINGS_EMAIL",function(){return c}),n.d(e,"SETTINGS_FREQUENCY",function(){return o}),n.d(e,"SETTINGS_VERIFICATION",function(){return u}),n.d(e,"SETTINGS_MIXPANELID",function(){return s}),n.d(e,"URL_PRICING",function(){return a}),n.d(e,"URL_SUPPORT",function(){return f});var r="license-key",i="subscription-status",c="email",o="frequency",u="verification",s="mixpanel-unique-id",a="http://getstark.co/pricing",f="http://support.getstark.co/"},"./src/sketch/helpers/utilities.js":
/*!*****************************************!*\
  !*** ./src/sketch/helpers/utilities.js ***!
  \*****************************************/
/*! exports provided: openURL, saveSetting, saveAllSettings, loadSetting, loadAllSettings, showToast, loadMixpanelDistinctId, callMixpanelTrackEvent, convertHexToRGB, getArtboardNames, getSelectedArtboard, exportArtboard, getArtboardSize */function(t,e,n){"use strict";n.r(e),n.d(e,"openURL",function(){return f}),n.d(e,"saveSetting",function(){return S}),n.d(e,"saveAllSettings",function(){return l}),n.d(e,"loadSetting",function(){return d}),n.d(e,"loadAllSettings",function(){return T}),n.d(e,"showToast",function(){return I}),n.d(e,"loadMixpanelDistinctId",function(){return p}),n.d(e,"callMixpanelTrackEvent",function(){return E}),n.d(e,"convertHexToRGB",function(){return h}),n.d(e,"getArtboardNames",function(){return N}),n.d(e,"getSelectedArtboard",function(){return g}),n.d(e,"exportArtboard",function(){return _}),n.d(e,"getArtboardSize",function(){return y});var r=n(/*! sketch */"sketch"),i=n.n(r),c=n(/*! sketch/settings */"sketch/settings"),o=n.n(c),u=n(/*! sketch/ui */"sketch/ui"),s=n.n(u),a=n(/*! ./constants */"./src/sketch/helpers/constants.js"),f=function(t){var e=NSURL.URLWithString(t);NSWorkspace.sharedWorkspace().openURL(e)},S=function(t,e){o.a.setSettingForKey("com.stark.".concat(t),e)},l=function(t){S(a.SETTINGS_LICENSE,t.licenseKey),S(a.SETTINGS_STATUS,"valid"),S(a.SETTINGS_EMAIL,t.email),S(a.SETTINGS_FREQUENCY,t.frequency),S(a.SETTINGS_VERIFICATION,(new Date).getMonth())},d=function(t){return o.a.settingForKey("com.stark.".concat(t))},T=function(){return{licenseKey:d(a.SETTINGS_LICENSE),status:d(a.SETTINGS_STATUS),email:d(a.SETTINGS_EMAIL),frequency:d(a.SETTINGS_FREQUENCY),verificationDate:d(a.SETTINGS_VERIFICATION)}},I=function(t){s.a.message(t)},p=function(){var t=d(a.SETTINGS_MIXPANELID);return t||(t=((new Date).getUTCMilliseconds().toString()+(new Date).getTime().toString()).toString(),S(a.SETTINGS_MIXPANELID,t)),t},E=function(t,e,n,r){t.executeJavaScript("handleMixpanelEvent('".concat(e,"', '").concat(JSON.stringify({distinct_id:p(),eventDetailsPrimary:n,eventDetailsSecondary:r}),"')")).catch(console.error)},h=function(t){return{r:parseInt(t.slice(1,3),16),g:parseInt(t.slice(3,5),16),b:parseInt(t.slice(5,7),16),a:parseInt(t.slice(7,9),16)/255}},N=function(t){var e=t.selectedPage,n=g(t),r=[];return e.layers.forEach(function(t){("Artboard"===t.type||"SymbolMaster"===t.type)&&r.push({id:t.id,name:t.name,isSelected:n==t.id})}),r.reverse()},g=function(t){var e;return t.selectedLayers.layers.forEach(function(t){e=t.sketchObject.parentArtboard()}),e&&(e=e.objectID()),e},_=function(t){return i.a.export(t,{scales:"2",formats:"png",output:!1}).toString("base64")},y=function(t){return{width:2*t.frame.width,height:2*t.frame.height}}},"./src/sketch/refresh.js":
/*!*******************************!*\
  !*** ./src/sketch/refresh.js ***!
  \*******************************/
/*! exports provided: default */function(t,e,n){"use strict";n.r(e);var r=n(/*! ./helpers/utilities */"./src/sketch/helpers/utilities.js"),i=n(/*! ./helpers/constants */"./src/sketch/helpers/constants.js");e.default=function(){[i.SETTINGS_LICENSE,i.SETTINGS_STATUS,i.SETTINGS_EMAIL,i.SETTINGS_FREQUENCY,i.SETTINGS_VERIFICATION].forEach(function(t){r.saveSetting(t,"")}),r.showToast("Your subscription refreshed! Head back to the registration screen to re-enter your license key.")}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(t,e){t.exports=require("sketch")},"sketch/settings":
/*!**********************************!*\
  !*** external "sketch/settings" ***!
  \**********************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/settings")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/ui")}});"default"===t&&"function"==typeof n?n(e):n[t](e)}that.onRun=__skpm_run.bind(this,"default");